defaults:
  run:
    shell: bash

name: Build & Test

on:
  push:
    branches-ignore:
      - main

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Install PNPM
        run: npm install -g pnpm

      - name: Get PNPM config store path
        id: pnpm-store
        run: echo "name=dir::$(pnpm config get store)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v2
        id: pnpm-cache
        with:
          path: ~/.pnpm-store
          key: Linux-pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install
